name: MacOSTest

on:
  workflow_dispatch:

jobs:
  hyp3-isce2:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            repository: 'ASFHyP3/hyp3-isce2'

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-environment: true
          environment-file: environment.yml

      - name: Development install
        run: pip install -e .

      - name: Run Example Workflow
        env: 
            EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
            EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD}}
            ESA_USERNAME: ${{ secrets.ESA_USERNAME }}
            ESA_PASSWORD: ${{ secrets.ESA_PASSWORD}}
        run: |
            python -m hyp3_isce2 ++process insar_tops_burst \
            S1_136231_IW2_20200604T022312_VV_7C85-BURST \
            S1_136231_IW2_20200616T022313_VV_5D11-BURST \
            --looks 20x4 \
            --apply-water-mask False