# Single reference + list of secondary bursts
name: ParallelPairs

on:
  workflow_dispatch:
    inputs:
      reference:
        type: string
        required: true
        description: Reference Burst
        default: S1_023790_IW1_20231206T121430_VV_D537-BURST

# TODO: dynamic creation of secondary list (n subsequent pairs)

jobs:
  hyp3-isce2-matrix:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        secondary: [S1_023790_IW1_20231218T121430_VV_B9A6-BURST,S1_023790_IW1_20231230T121429_VV_B9CD-BURST,S1_023790_IW1_20240111T121428_VV_5827-BURST]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            repository: 'ASFHyP3/hyp3-isce2'

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-environment: true
          environment-file: environment.yml

      - name: Development install
        run: pip install -e .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-west-2

      - name: Get Bucket Prefix
        env:
          REF: ${{ inputs.reference }}
          SEC: ${{ inputs.secondary }}
        run: |
          PREFIX=${REF:14:8}_${SEC:14:8}
          echo "PREFIX=${PREFIX}" >> $GITHUB_ENV

      - name: Run Example Workflow
        env: 
            EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
            EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD}}
            ESA_USERNAME: ${{ secrets.ESA_USERNAME }}
            ESA_PASSWORD: ${{ secrets.ESA_PASSWORD}}
        run: |
            python -m hyp3_isce2 ++process insar_tops_burst \
            ${{ inputs.reference }}  \
            ${{ matrix.secondary }}  \
            --looks 20x4 \
            --apply-water-mask False \
            --bucket fufiters \
            --bucket-prefix $PREFIX

      - name: Upload Hyp3 Output
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PREFIX }}
          path: S1*.zip