name: SingleBurstDenseOffsets

on:
  workflow_dispatch:
    inputs:
      reference:
        type: string
        required: true
        description: Reference Burst
        default: S1_023790_IW1_20230621T121426_VV_BAD8-BURST
      secondary:
        type: string
        required: true
        description: Secondary Burst
        default: S1_023790_IW1_20230703T121427_VV_F9AB-BURST
      nlooks:
          type: choice
          required: true
          description: Range x Azimuth Looks
          default: 5x1
          options: 
            - 20x4
            - 10x2
            - 5x1

jobs:
  hyp3-isce2:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            repository: 'relativeorbit/hyp3-isce2'
            ref: 'denseoffsets'

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-environment: true
          environment-file: environment.yml

      - name: Development install
        run: pip install -e .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-west-2

      - name: Get Bucket Prefix
        env:
          REF: ${{ inputs.reference }}
          SEC: ${{ inputs.secondary }}
        run: |
          PREFIX=${REF:14:8}_${SEC:14:8}
          echo "PREFIX=${PREFIX}" >> $GITHUB_ENV

      # NOTE: avoids RuntimeError: context has already been set
      # https://github.com/isce-framework/isce2/issues/146
      - name: Patch DenseAmpcor
        run: |
          AMPCOR=/home/runner/micromamba/envs/hyp3-isce2/lib/python3.11/site-packages/isce/components/mroipac/ampcor/DenseAmpcor.py
          sed -i '315,318 {s/^/#/;}' $AMPCOR
          sed -n 312,320p $AMPCOR

      - name: Run Example Workflow
        env: 
            EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
            EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD}}
            ESA_USERNAME: ${{ secrets.ESA_USERNAME }}
            ESA_PASSWORD: ${{ secrets.ESA_PASSWORD}}
        run: |
            python -m hyp3_isce2 ++process insar_tops_burst \
            ${{ inputs.reference }}  \
            ${{ inputs.secondary }}  \
            --looks ${{ inputs.nlooks }} \
            --apply-water-mask False \
            --bucket fufiters \
            --bucket-prefix $PREFIX

      - name: Upload Hyp3 Output
        uses: actions/upload-artifact@v4
        with:
          name: hyp3-isce2
          path: S1*.zip