name: SingleBurstCustom

on:
  workflow_dispatch:
    inputs:
      reference:
        type: string
        required: true
        description: reference burst
        default: S1_136231_IW2_20200604T022312_VV_7C85-BURST
      secondary:
        type: string
        required: true
        description: secondary burst
        default: S1_136231_IW2_20200616T022313_VV_5D11-BURST

# TODO: parse inputs for dates to use in bucket-prefix

jobs:
  hyp3-isce2:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            repository: 'ASFHyP3/hyp3-isce2'

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-environment: true
          environment-file: environment.yml

      - name: Development install
        run: pip install -e .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-west-2

      - name: Run Example Workflow
        env: 
            EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
            EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD}}
            ESA_USERNAME: ${{ secrets.ESA_USERNAME }}
            ESA_PASSWORD: ${{ secrets.ESA_PASSWORD}}
        run: |
            python -m hyp3_isce2 ++process insar_tops_burst \
            ${{ inputs.reference }}  \
            ${{ inputs.secondary }}  \
            --looks 20x4 \
            --apply-water-mask False \
            --bucket fufiters \
            --bucket-prefix singleburst_custom

      - name: Upload Hyp3 Output
        uses: actions/upload-artifact@v4
        with:
          name: hyp3-isce2
          path: S1*.zip